site_name: Integrity Policy Enforcement
repo_url: https://github.com/microsoft/ipe
copyright: Copyright (c) Microsoft. All rights reserved.
site_description: "Integrity Policy Enforcement (IPE) Documentation"
site_url: "https://microsoft.github.io/ipe"
theme:
  name: 'mkdocs'

nav:
  - Home: "index.md"
  - Usage:  
    - Overview: "usage/index.md"
    - Properties: "usage/properties.md"
    - Deploying Policies: "usage/deployment.md"
    - Example Policies: "usage/examples.md"
    - Audit Events: "usage/events.md"
  - Technical:
    - Threat Model: "technical/threat-model.md"
    - Technical Diagrams: "technical/diagrams.md"
  - Other:
    - FAQ: "faq.md"
    - Presentations: "presentations.md"
    - Attribution: "attribution.md"
    - License: "license.md"
